2023-02-02 10:17:16,102 |           flt.pandoc |    ERROR | Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/foliant/backends/base.py", line 66, in apply_preprocessor
    preprocessor_module = import_module(f'foliant.preprocessors.{preprocessor_name}')
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'foliant.preprocessors.anchors'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/foliant/utils.py", line 158, in spinner
    yield
  File "/usr/local/lib/python3.8/dist-packages/foliant/backends/base.py", line 76, in apply_preprocessor
    raise ModuleNotFoundError(
ModuleNotFoundError: Preprocessor anchors is not installed

2023-02-02 10:17:16,105 |           flt.pandoc |    ERROR | Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/foliant/backends/base.py", line 66, in apply_preprocessor
    preprocessor_module = import_module(f'foliant.preprocessors.{preprocessor_name}')
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'foliant.preprocessors.csvtables'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/foliant/utils.py", line 158, in spinner
    yield
  File "/usr/local/lib/python3.8/dist-packages/foliant/backends/base.py", line 76, in apply_preprocessor
    raise ModuleNotFoundError(
ModuleNotFoundError: Preprocessor csvtables is not installed

2023-02-02 10:17:17,102 |           flt.pandoc |    ERROR | Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/foliant/backends/base.py", line 66, in apply_preprocessor
    preprocessor_module = import_module(f'foliant.preprocessors.{preprocessor_name}')
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'foliant.preprocessors.flags'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/foliant/utils.py", line 158, in spinner
    yield
  File "/usr/local/lib/python3.8/dist-packages/foliant/backends/base.py", line 76, in apply_preprocessor
    raise ModuleNotFoundError(
ModuleNotFoundError: Preprocessor flags is not installed

2023-02-02 10:17:17,103 |           flt.pandoc |    ERROR | Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/foliant/backends/base.py", line 66, in apply_preprocessor
    preprocessor_module = import_module(f'foliant.preprocessors.{preprocessor_name}')
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'foliant.preprocessors.graphviz'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/foliant/utils.py", line 158, in spinner
    yield
  File "/usr/local/lib/python3.8/dist-packages/foliant/backends/base.py", line 76, in apply_preprocessor
    raise ModuleNotFoundError(
ModuleNotFoundError: Preprocessor graphviz is not installed

2023-02-02 10:17:17,352 |           flt.pandoc |    ERROR | Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/foliant/backends/base.py", line 66, in apply_preprocessor
    preprocessor_module = import_module(f'foliant.preprocessors.{preprocessor_name}')
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'foliant.preprocessors.macros'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/foliant/utils.py", line 158, in spinner
    yield
  File "/usr/local/lib/python3.8/dist-packages/foliant/backends/base.py", line 76, in apply_preprocessor
    raise ModuleNotFoundError(
ModuleNotFoundError: Preprocessor macros is not installed

2023-02-02 10:17:17,353 |           flt.pandoc |    ERROR | Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/foliant/backends/base.py", line 66, in apply_preprocessor
    preprocessor_module = import_module(f'foliant.preprocessors.{preprocessor_name}')
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'foliant.preprocessors.mermaid'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/foliant/utils.py", line 158, in spinner
    yield
  File "/usr/local/lib/python3.8/dist-packages/foliant/backends/base.py", line 76, in apply_preprocessor
    raise ModuleNotFoundError(
ModuleNotFoundError: Preprocessor mermaid is not installed

2023-02-02 10:17:17,354 |           flt.pandoc |    ERROR | Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/foliant/backends/base.py", line 66, in apply_preprocessor
    preprocessor_module = import_module(f'foliant.preprocessors.{preprocessor_name}')
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'foliant.preprocessors.multilinetables'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/foliant/utils.py", line 158, in spinner
    yield
  File "/usr/local/lib/python3.8/dist-packages/foliant/backends/base.py", line 76, in apply_preprocessor
    raise ModuleNotFoundError(
ModuleNotFoundError: Preprocessor multilinetables is not installed

2023-02-02 10:17:17,354 |           flt.pandoc |    ERROR | Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/foliant/backends/base.py", line 66, in apply_preprocessor
    preprocessor_module = import_module(f'foliant.preprocessors.{preprocessor_name}')
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'foliant.preprocessors.plantuml'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/foliant/utils.py", line 158, in spinner
    yield
  File "/usr/local/lib/python3.8/dist-packages/foliant/backends/base.py", line 76, in apply_preprocessor
    raise ModuleNotFoundError(
ModuleNotFoundError: Preprocessor plantuml is not installed

2023-02-02 10:17:17,355 |           flt.pandoc |    ERROR | Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/foliant/backends/base.py", line 66, in apply_preprocessor
    preprocessor_module = import_module(f'foliant.preprocessors.{preprocessor_name}')
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'foliant.preprocessors.runcommands'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/foliant/utils.py", line 158, in spinner
    yield
  File "/usr/local/lib/python3.8/dist-packages/foliant/backends/base.py", line 76, in apply_preprocessor
    raise ModuleNotFoundError(
ModuleNotFoundError: Preprocessor runcommands is not installed

